<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/12/07 20:44:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
