<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/12/11 15:02:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=jobeet',
  'username' => 'postgres',
  'password' => 'alexis',
  'name' => 'doctrine',
)),);
